### ISSUE TITLE
Extract `expand-vertices` into its own module

### ISSUE THREAD

**Issue by kevzettler** [chinedufn/load-collada-dae#1]
Just saw:
https://github.com/chinedufn/load-collada-dae/blob/master/src/expand-vertices.js#L1-L2

when I was working on porting for https://github.com/regl-project/regl/issues/186#issuecomment-278982315

About to copy/paste it my self.

**Comment by chinedufn** [comment]
Published https://github.com/chinedufn/expand-vertex-data
