### ISSUE TITLE
Why 2 possible drawModel functions?

### ISSUE THREAD

**Issue by kevzettler** [chinedufn/load-collada-dae#2]
Hi Chinedufn,

Let me know if you would rather I send you an email for questions like these instead of filling issues.

I'm wondering what's going on with:
https://github.com/chinedufn/load-collada-dae/blob/master/src/load-collada-dae.js#L51-L54

It looks like `drawModel2` might fail to create, and fallback to `drawModel` is that correct? Why would drawModel2 fail?

The two draw functions seem significantly different and wondering what the best one to port to regl would be.

**Comment by chinedufn** [comment]
@kevzettler thanks a lot for the consideration. I definitely prefer issues so keep feeling very free to fire away.

So the story here is that `load-collada-dae` is a very experimental library that is very much a work in progress. And with that we're still in "throw stuff in until tests finally pass" mode. 

That `drawModel` function doesn't even get called anymore. That `||` statement is just some leftover cruft from when I couldn't get it working.

---

`drawModel` was the original draw function that was hard coded to support skeletal animation with a specific default shader.

I recently wanted to support [passing in a custom shader](https://github.com/chinedufn/load-collada-dae/blob/master/test/custom-shader/basic-custom-shader_test.js#L89) so I started working on that `drawModel2` function (as a replacement for the original `drawModel`).

The `drawModel2` function is my first stab at a way to automatically generate an optimized JavaScript draw function based on your shader.. Only got it working around a week ago and plan to pull it out into a tested repo.

---

But that `drawModel2` function is actually inspired by `regl`. `regl` already does all of this for you, so you don't need to port either of these draw functions. 

If you pass `regl` your shader, and the right attributes and uniforms you should be good to go.

---

So if you take this [vertex shader](https://github.com/chinedufn/collada-dae-parser/blob/2df7f53e44e33649db88ca2baa917dbb96a1c96f/demo/animated-model/shader/vertex.glsl) and this [fragment shader](https://github.com/chinedufn/collada-dae-parser/blob/2df7f53e44e33649db88ca2baa917dbb96a1c96f/demo/animated-model/shader/fragment.glsl) and paste them into `regl` you should be most of the way there.

You can get the attributes that you need by running that `expand-vertex-data` function on what data that you get back from `collada-dae-parser` and then passing those arrays into `regl`

**Comment by kevzettler** [comment]
Thanks for the thorough reply. 

> So if you take this vertex shader and this fragment shader and paste them into regl you should be most of the way there.
> 
> You can get the attributes that you need by running that expand-vertex-data function on what data that you get back from collada-dae-parser and then passing those arrays into regl

Cool, I have this approach in progress. I Was tracing the data flow through the `drawModel` functions to ensure I have the correct attributes and uniforms being passed.

**Comment by chinedufn** [comment]
Nice! Super, super exciting

And yup, sorry for that confusion. Just removed the old function 597ff4e8dd27ed87fae61e347adad332e836657f . 

README is out of date right now, but here's a better look at how that draw function `load-collada-dae` gets used.

---

Thanks for pointing this out!
